# Generated by Django 6.0.4 on 2026-05-18 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
